// Generated by OmikujiBot Config Editor
// Generated at: 2026-01-09T11:52:41.512Z
// 
// このファイルはコンフィグエディターで生成されました。
// 手動で編集する場合は、JSON形式の構文エラーにご注意ください。

const omikujiData = {
  "meta": {
    "id": "210bc358-d1db-47f5-8059-debedcb25577",
    "name": "unknown",
    "description": "",
    "version": "0.0.0",
    "generatorName": "unknown-generator",
    "generatorVersion": "1.x.x",
    "dataVersion": 1,
    "author": "unknown",
    "tags": [],
    "license": "CC-BY 4.0"
  },
  "jsonMerge": [],
  "comments": {},
  "timers": {},
  "actionSets": {},
  "placeholders": {},
  "characters": {},
  "components": {
    "conditions": [
      "bubble",
      "toast"
    ],
    "bubble": {
      "showCharacters": {
        "center": [],
        "slot1": [],
        "slot2": [],
        "slot3": [],
        "slot4": []
      },
      "defaultColor": {
        "isTheme": true,
        "daisyUiTheme": "dark",
        "backFrom": "primary",
        "backTo": "secondary",
        "nameColor": "#212121",
        "textColor": "#212121",
        "backgroundColor": "#FAFAFA"
      },
      "characterSize": 48,
      "fontFamily": "default",
      "bubbleMotionEnter": "slideUp",
      "bubbleTextAnimate": false,
      "bubbleTextSpeed": 50
    },
    "toast": {
      "defaultColor": {
        "isTheme": true,
        "daisyUiTheme": "dark",
        "backFrom": "primary",
        "backTo": "secondary",
        "nameColor": "#212121",
        "textColor": "#212121",
        "backgroundColor": "#FAFAFA"
      },
      "showToastsOnRight": true,
      "showToastsCharacter": false,
      "showThumbnail": []
    },
    "ranking": {
      "targetScriptKeys": [
        "basicList"
      ],
      "title": "🍉スイカランキング🍉",
      "limit": 5,
      "sortOrder": "new",
      "color": "lofi"
    },
    "counter": {
      "ruleKey": null,
      "target": "draw",
      "label": "Counter",
      "showCounter": true,
      "firstValue": 0,
      "isDirectionUp": true,
      "maxUsers": 1,
      "color": {
        "daisyUiTheme": "dark",
        "backFrom": "primary",
        "backTo": "secondary"
      }
    }
  },
  "featureUsage": {
    "usage": {
      "comments": "basic",
      "timers": "basic",
      "actionSets": "basic",
      "placeholders": "basic",
      "characters": "basic"
    },
    "components": [],
    "gameScripts": [],
    "developer": {
      "licenseVisible": "basic",
      "jsonMergeSettings": "basic"
    }
  },
  "settings": {
    "commentType": "OneComme",
    "licenseKeyHash": "",
    "daisyUiTheme": "dark"
  }
};

if (typeof window !== 'undefined') window.omikujiData = omikujiData;
