// src/editor/helpers/presetsExport/generateContent.ts

// .js での出力テンプレート
export const generateJsContent = (configData: string) => {
  const timestamp = new Date().toISOString()
  return `// Generated by OmikujiBot Config Editor
// Generated at: ${timestamp}
// 
// このファイルはコンフィグエディターで生成されました。
// 手動で編集する場合は、JSON形式の構文エラーにご注意ください。

const omikujiData = ${configData};

if (typeof window !== 'undefined') window.omikujiData = omikujiData;
`
}

// .json での出力テンプレート
export const generateJsonContent = (configData: string) => {
  const parsedData = JSON.parse(configData)
  const templateData = { ...parsedData }
  return JSON.stringify(templateData)
}
